### ISSUE TITLE
Json Schema Button Double Click 

### ISSUE THREAD

**Issue by ammarkhan967** [BlueBaseJS/plugin-json-schema-components#32]
Json Schema button onclick is working by double clicking the button

## Description
Json Schema button onclick is working by double clicking the button

## Expected Behavior
Form should submit on one click 

## Actual Behavior
Form is submitting on double clicking of button

## Possible Fix
Possible fix will be in json schema button

## Steps to Reproduce

1. Clicking on any Form 

## Context
The user has to click twice for the submission of form.

## Screenshots
Run a Form Component of Mevris (Required)

**Comment by artalat** [comment]
I've spent some time on this bug. Seems like it only happens when text input is focused and submit is pressed. On first press, text input loses focus by firing blur event, and the second press button click event is fired.
